name: Test

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    name: Test upload artifact to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update Github Release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - *.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save file to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestFile
          path: file.txt
