name: Test

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    name: Test upload artifact to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: 'v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)'
          tagRegexGroup: 1

      - name: pubspec release
        run: |
          sed -i 's/version: 1.0.0+1/version: '${{ steps.tagName.outputs.tag }}'/g' pubspec.yaml|
          echo "Tagged pubspec.yaml"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.yaml"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Save file to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestFile
          path: pubspec.yaml
